## Numpy Library

In [2]:
import numpy as np

In [3]:
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [4]:
#Reshape
b=a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [5]:
for i in range(1, 6):
    print(f"\nPerson {i}")
    weight = float(input("Enter weight in kg: "))
    height = float(input("Enter height in meters: "))

    bmi = weight / (height * height)

    print(f"BMI of Person {i} is: {bmi:.2f}")


Person 1


Enter weight in kg:  40
Enter height in meters:  1.68


BMI of Person 1 is: 14.17

Person 2


Enter weight in kg:  45
Enter height in meters:  1.70


BMI of Person 2 is: 15.57

Person 3


Enter weight in kg:  50
Enter height in meters:  1.80


BMI of Person 3 is: 15.43

Person 4


Enter weight in kg:  55
Enter height in meters:  1.65


BMI of Person 4 is: 20.20

Person 5


Enter weight in kg:  60
Enter height in meters:  1.90


BMI of Person 5 is: 16.62


In [13]:
import numpy as np
heights = np.array([1.70, 1.60, 1.80, 1.55, 1.68])
weights = np.array([65, 70, 55, 50, 40])
bmi = weights / (heights ** 2)
bmi_rounded = np.round(bmi, 2)
for i in range(len(bmi_rounded)):
    print(f" BMI = {bmi_rounded[i]} of a student {i+1} ")

 BMI = 22.49 of a student 1 
 BMI = 27.34 of a student 2 
 BMI = 16.98 of a student 3 
 BMI = 20.81 of a student 4 
 BMI = 14.17 of a student 5 
